server:
  port: 90
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-response: true
    session:
      timeout: 1800 # 60? * 30
spring:
  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    enabled: true
  devtools:
    livereload:
      enabled: true
  security:
    user:
      name: user
      password: 123


  datasource:
    hikari:
      jdbc-url: "jdbc:h2:mem:testDB"
      username: "sa"
      password: ""
  h2:
    console:
      enabled: true
      path: /h2-console