server:
  port: 90
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-response: true
    session:
      timeout: 10m

spring:
  security:
    user:
      name: user
      password: 123
  session:
    jdbc:
      initialize-schema: always

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost/testDB?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: nyt00630!

  mustache:
    servlet:
      expose-request-attributes: true
